# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BrowserDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BrowserDialog(object):
    def setupUi(self, BrowserDialog):
        BrowserDialog.setObjectName("BrowserDialog")
        BrowserDialog.resize(400, 300)

        self.retranslateUi(BrowserDialog)
        QtCore.QMetaObject.connectSlotsByName(BrowserDialog)

    def retranslateUi(self, BrowserDialog):
        _translate = QtCore.QCoreApplication.translate
        BrowserDialog.setWindowTitle(_translate("BrowserDialog", "Dialog"))
