# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ManagerDataDialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ManagerDataDialog(object):
    def setupUi(self, ManagerDataDialog):
        ManagerDataDialog.setObjectName("ManagerDataDialog")
        ManagerDataDialog.resize(600, 500)
        ManagerDataDialog.setMinimumSize(QtCore.QSize(600, 500))
        self.verticalLayout = QtWidgets.QVBoxLayout(ManagerDataDialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(ManagerDataDialog)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dateStart = QtWidgets.QDateEdit(self.widget)
        self.dateStart.setMinimumSize(QtCore.QSize(0, 36))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.dateStart.setFont(font)
        self.dateStart.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2020, 3, 7), QtCore.QTime(0, 0, 0)))
        self.dateStart.setCalendarPopup(True)
        self.dateStart.setObjectName("dateStart")
        self.horizontalLayout.addWidget(self.dateStart)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMinimumSize(QtCore.QSize(0, 36))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.dateEnd = QtWidgets.QDateEdit(self.widget)
        self.dateEnd.setMinimumSize(QtCore.QSize(0, 36))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.dateEnd.setFont(font)
        self.dateEnd.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2020, 3, 7), QtCore.QTime(0, 0, 0)))
        self.dateEnd.setCalendarPopup(True)
        self.dateEnd.setObjectName("dateEnd")
        self.horizontalLayout.addWidget(self.dateEnd)
        self.btnSearch = QtWidgets.QPushButton(self.widget)
        self.btnSearch.setMinimumSize(QtCore.QSize(0, 36))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btnSearch.setFont(font)
        self.btnSearch.setObjectName("btnSearch")
        self.horizontalLayout.addWidget(self.btnSearch)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(ManagerDataDialog)
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tbData = QtWidgets.QTableWidget(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.tbData.setFont(font)
        self.tbData.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tbData.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbData.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tbData.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbData.setObjectName("tbData")
        self.tbData.setColumnCount(9)
        self.tbData.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbData.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbData.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbData.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbData.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbData.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbData.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbData.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbData.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbData.setHorizontalHeaderItem(8, item)
        self.tbData.horizontalHeader().setDefaultSectionSize(40)
        self.tbData.horizontalHeader().setMinimumSectionSize(40)
        self.tbData.verticalHeader().setDefaultSectionSize(40)
        self.tbData.verticalHeader().setMinimumSectionSize(40)
        self.horizontalLayout_3.addWidget(self.tbData)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(ManagerDataDialog)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 160))
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 160))
        self.widget_3.setStyleSheet("")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.widget_3)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_4 = QtWidgets.QWidget(self.groupBox)
        self.widget_4.setStyleSheet("")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_6 = QtWidgets.QWidget(self.widget_4)
        self.widget_6.setMinimumSize(QtCore.QSize(0, 36))
        self.widget_6.setMaximumSize(QtCore.QSize(16777215, 36))
        self.widget_6.setStyleSheet("")
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.widget_6)
        self.label_2.setMinimumSize(QtCore.QSize(0, 36))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 36))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.dateEdit = QtWidgets.QDateEdit(self.widget_6)
        self.dateEdit.setMinimumSize(QtCore.QSize(0, 36))
        self.dateEdit.setMaximumSize(QtCore.QSize(16777215, 36))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.dateEdit.setFont(font)
        self.dateEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2020, 3, 7), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setMaximumDate(QtCore.QDate(9999, 12, 31))
        self.dateEdit.setMinimumDate(QtCore.QDate(2020, 3, 7))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_5.addWidget(self.dateEdit)
        self.label_3 = QtWidgets.QLabel(self.widget_6)
        self.label_3.setMinimumSize(QtCore.QSize(0, 36))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 36))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.issueEdit = QtWidgets.QLineEdit(self.widget_6)
        self.issueEdit.setMinimumSize(QtCore.QSize(60, 36))
        self.issueEdit.setMaximumSize(QtCore.QSize(60, 36))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.issueEdit.setFont(font)
        self.issueEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.issueEdit.setObjectName("issueEdit")
        self.horizontalLayout_5.addWidget(self.issueEdit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.widget_6)
        self.widget_7 = QtWidgets.QWidget(self.widget_4)
        self.widget_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_7.setObjectName("widget_7")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_7)
        self.gridLayout.setObjectName("gridLayout")
        self.n1Edit = QtWidgets.QLineEdit(self.widget_7)
        self.n1Edit.setMinimumSize(QtCore.QSize(36, 36))
        self.n1Edit.setMaximumSize(QtCore.QSize(36, 36))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.n1Edit.setFont(font)
        self.n1Edit.setAlignment(QtCore.Qt.AlignCenter)
        self.n1Edit.setObjectName("n1Edit")
        self.gridLayout.addWidget(self.n1Edit, 0, 0, 1, 1)
        self.n2Edit = QtWidgets.QLineEdit(self.widget_7)
        self.n2Edit.setMinimumSize(QtCore.QSize(36, 36))
        self.n2Edit.setMaximumSize(QtCore.QSize(36, 36))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.n2Edit.setFont(font)
        self.n2Edit.setAlignment(QtCore.Qt.AlignCenter)
        self.n2Edit.setObjectName("n2Edit")
        self.gridLayout.addWidget(self.n2Edit, 0, 1, 1, 1)
        self.n3Edit = QtWidgets.QLineEdit(self.widget_7)
        self.n3Edit.setMinimumSize(QtCore.QSize(36, 36))
        self.n3Edit.setMaximumSize(QtCore.QSize(36, 36))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.n3Edit.setFont(font)
        self.n3Edit.setAlignment(QtCore.Qt.AlignCenter)
        self.n3Edit.setObjectName("n3Edit")
        self.gridLayout.addWidget(self.n3Edit, 0, 2, 1, 1)
        self.n4Edit = QtWidgets.QLineEdit(self.widget_7)
        self.n4Edit.setMinimumSize(QtCore.QSize(36, 36))
        self.n4Edit.setMaximumSize(QtCore.QSize(36, 36))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.n4Edit.setFont(font)
        self.n4Edit.setAlignment(QtCore.Qt.AlignCenter)
        self.n4Edit.setObjectName("n4Edit")
        self.gridLayout.addWidget(self.n4Edit, 0, 3, 1, 1)
        self.n5Edit = QtWidgets.QLineEdit(self.widget_7)
        self.n5Edit.setMinimumSize(QtCore.QSize(36, 36))
        self.n5Edit.setMaximumSize(QtCore.QSize(36, 36))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.n5Edit.setFont(font)
        self.n5Edit.setAlignment(QtCore.Qt.AlignCenter)
        self.n5Edit.setObjectName("n5Edit")
        self.gridLayout.addWidget(self.n5Edit, 0, 4, 1, 1)
        self.n6Edit = QtWidgets.QLineEdit(self.widget_7)
        self.n6Edit.setMinimumSize(QtCore.QSize(36, 36))
        self.n6Edit.setMaximumSize(QtCore.QSize(36, 36))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.n6Edit.setFont(font)
        self.n6Edit.setAlignment(QtCore.Qt.AlignCenter)
        self.n6Edit.setObjectName("n6Edit")
        self.gridLayout.addWidget(self.n6Edit, 0, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget_7)
        self.label_4.setMinimumSize(QtCore.QSize(36, 36))
        self.label_4.setMaximumSize(QtCore.QSize(36, 36))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 6, 1, 1)
        self.n7Edit = QtWidgets.QLineEdit(self.widget_7)
        self.n7Edit.setMinimumSize(QtCore.QSize(36, 36))
        self.n7Edit.setMaximumSize(QtCore.QSize(36, 36))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.n7Edit.setFont(font)
        self.n7Edit.setAlignment(QtCore.Qt.AlignCenter)
        self.n7Edit.setObjectName("n7Edit")
        self.gridLayout.addWidget(self.n7Edit, 0, 7, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget_7)
        self.label_5.setMinimumSize(QtCore.QSize(36, 36))
        self.label_5.setMaximumSize(QtCore.QSize(36, 36))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget_7)
        self.label_6.setMinimumSize(QtCore.QSize(36, 36))
        self.label_6.setMaximumSize(QtCore.QSize(36, 36))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget_7)
        self.label_7.setMinimumSize(QtCore.QSize(36, 36))
        self.label_7.setMaximumSize(QtCore.QSize(36, 36))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget_7)
        self.label_8.setMinimumSize(QtCore.QSize(36, 36))
        self.label_8.setMaximumSize(QtCore.QSize(36, 36))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget_7)
        self.label_9.setMinimumSize(QtCore.QSize(36, 36))
        self.label_9.setMaximumSize(QtCore.QSize(36, 36))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 4, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget_7)
        self.label_10.setMinimumSize(QtCore.QSize(36, 36))
        self.label_10.setMaximumSize(QtCore.QSize(36, 36))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 5, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget_7)
        self.label_11.setMinimumSize(QtCore.QSize(36, 36))
        self.label_11.setMaximumSize(QtCore.QSize(36, 36))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 7, 1, 1)
        self.verticalLayout_2.addWidget(self.widget_7)
        self.horizontalLayout_4.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.groupBox)
        self.widget_5.setMinimumSize(QtCore.QSize(80, 0))
        self.widget_5.setMaximumSize(QtCore.QSize(80, 16777215))
        self.widget_5.setStyleSheet("")
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.pushButton_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.pushButton = QtWidgets.QPushButton(self.widget_5)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.horizontalLayout_4.addWidget(self.widget_5)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.verticalLayout.addWidget(self.widget_3)

        self.retranslateUi(ManagerDataDialog)
        self.btnSearch.clicked.connect(ManagerDataDialog.doSearch)
        self.pushButton.clicked.connect(ManagerDataDialog.doSave)
        self.pushButton_2.clicked.connect(ManagerDataDialog.doCancel)
        QtCore.QMetaObject.connectSlotsByName(ManagerDataDialog)

    def retranslateUi(self, ManagerDataDialog):
        _translate = QtCore.QCoreApplication.translate
        ManagerDataDialog.setWindowTitle(_translate("ManagerDataDialog", "管理数据"))
        self.dateStart.setDisplayFormat(_translate("ManagerDataDialog", "yyyy-M-d"))
        self.label.setText(_translate("ManagerDataDialog", "至"))
        self.dateEnd.setDisplayFormat(_translate("ManagerDataDialog", "yyyy-M-d"))
        self.btnSearch.setText(_translate("ManagerDataDialog", "查询"))
        item = self.tbData.horizontalHeaderItem(0)
        item.setText(_translate("ManagerDataDialog", "日期"))
        item = self.tbData.horizontalHeaderItem(1)
        item.setText(_translate("ManagerDataDialog", "期号"))
        item = self.tbData.horizontalHeaderItem(2)
        item.setText(_translate("ManagerDataDialog", "1"))
        item = self.tbData.horizontalHeaderItem(3)
        item.setText(_translate("ManagerDataDialog", "2"))
        item = self.tbData.horizontalHeaderItem(4)
        item.setText(_translate("ManagerDataDialog", "3"))
        item = self.tbData.horizontalHeaderItem(5)
        item.setText(_translate("ManagerDataDialog", "4"))
        item = self.tbData.horizontalHeaderItem(6)
        item.setText(_translate("ManagerDataDialog", "5"))
        item = self.tbData.horizontalHeaderItem(7)
        item.setText(_translate("ManagerDataDialog", "6"))
        item = self.tbData.horizontalHeaderItem(8)
        item.setText(_translate("ManagerDataDialog", "7"))
        self.groupBox.setTitle(_translate("ManagerDataDialog", "编辑记录"))
        self.label_2.setText(_translate("ManagerDataDialog", "日期："))
        self.dateEdit.setDisplayFormat(_translate("ManagerDataDialog", "yyyy-M-d"))
        self.label_3.setText(_translate("ManagerDataDialog", "期号："))
        self.label_4.setText(_translate("ManagerDataDialog", "+"))
        self.label_5.setText(_translate("ManagerDataDialog", "1"))
        self.label_6.setText(_translate("ManagerDataDialog", "2"))
        self.label_7.setText(_translate("ManagerDataDialog", "3"))
        self.label_8.setText(_translate("ManagerDataDialog", "4"))
        self.label_9.setText(_translate("ManagerDataDialog", "5"))
        self.label_10.setText(_translate("ManagerDataDialog", "6"))
        self.label_11.setText(_translate("ManagerDataDialog", "7"))
        self.pushButton_2.setText(_translate("ManagerDataDialog", "取消"))
        self.pushButton.setText(_translate("ManagerDataDialog", "保存"))
